### ISSUE TITLE
Example in README question

### ISSUE THREAD

**Issue by xaocon** [bikeshedder/deadqueue#1]
I'm trying to get into concurrency more and tried running the code from the README and it just stalls. Curious if that's what it's supposed to do and I'm missing something or maybe I'm doing something wrong or the code isn't valid anymore. I'm using deadqueue 0.2 and tokio 1 with `full`.

**Comment by bikeshedder** [comment]
I wonder what I've been thinking there. That example is completely messed up:

It creates a limited queue with the wrong size, then pushes objects without calling `.await` or using `try_push` instead and the cherry on top is the missing termination logic. It seams that I've never actually ran that example for real but just extracted it from the unit tests breaking it at the same time.

Please have a look at the `test_parallel` example which makes a lot more sense: https://github.com/bikeshedder/deadqueue/blob/master/tests/limited.rs#L25

I'll update the README asap. :facepalm:

**Comment by bikeshedder** [comment]
I just updated the example in the README. It makes a lot more sense now. :sweat_smile: 

Thanks for reporting this. :+1:
