### ISSUE TITLE
Example in the readme deadlocks

### ISSUE THREAD

**Issue by culebron** [bikeshedder/deadqueue#2]
The README example compiles, but seems to be deadlocked.

main.rs is exactly the same code. My `Cargo.toml` is:

```[package]
name = "threadtest"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = {version = "1.14", features = ["sync", "macros", "rt-multi-thread", "time"]}
deadqueue = "0.2"

```

**Comment by bikeshedder** [comment]
I can't reproduce this behavior. When I run the example it doesn't deadlock. Neither in debug nor in release mode. That code is even run as part of the CI tests.

Could you check where it actually deadlocks? I don't see how this code could ever do that. :thinking:

**Comment by bikeshedder** [comment]
@culebron I'm unable to reproduce this and I haven't heard back from you for quite some time. Feel free to reopen this issue with some way to reproduce this.
